stages:
  dimensionality_reduction:
    cmd: kedro run --pipeline=dimensionality_reduction
    deps:
      - data/01_raw
      - conf/base/catalog.yml
      - src/proyect_machine/pipelines/unsupervised_learning/dimensionality_reduction
    outs:
      - data/02_intermediate/scaled_movies.parquet
      - data/07_model_output/X_pca.parquet
      - data/07_model_output/pca_variance.csv
      - data/07_model_output/X_tsne.parquet

  unsupervised_clustering:
    cmd: kedro run --pipeline=unsupervised_learning_clustering
    deps:
      - data/01_raw
      - conf/base/catalog.yml
      - src/proyect_machine/pipelines/unsupervised_learning/clustering
    outs:
      - data/07_model_output/cluster_results.json
      - data/08_reporting/movies_with_clusters.csv
