# ==========================================
# 📌 Parámetros Clasificación Supervisada
# ==========================================
target_col: vote_count

feature_cols:
  - revenue
  - budget
  - popularity
  - runtime
  - vote_average

test_size: 0.5
random_state: 42


# ==========================================
# 📌 Parámetros Unsupervised (PCA + Clustering)
# ==========================================
n_components: 2              # PCA components

# ---- DBSCAN ----
eps: 0.5
min_samples: 10

# ---- KMeans ----
kmeans_clusters: 5

# ---- Agglomerative / Hierarchical ----
hierarchical_clusters: 5
