movies_metadata:
  type: pandas.CSVDataSet
  filepath: data/01_raw/movies_metadata.csv



target_col: vote_count
feature_cols: ['revenue', 'budget', 'popularity', 'runtime', 'vote_average']
test_size: 0.5
random_state: 42
